apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/project297-311705/plant-disease
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    envTemplate:
      template: latest
kind: Config
